python test.py --plms --gpu_id 3 \
--ddim_steps 100 \
--outdir results/viton \
--config configs/viton512.yaml \
--dataroot /mnt/aix23904/아르포아/virtual_tryon/VITON-HD \
--ckpt /mnt/aix23904/아르포아/virtual_tryon/DCI-VTON-Virtual-Try-On/checkpoints/viton512.ckpt \
--n_samples 8 \
--seed 23 \
--scale 1 \
--H 512 \
--W 512 \
--unpaired